version: '3'

services:
    client:
        container_name: client
        build:
            context: ../
            dockerfile: docker/client.Dockerfile
        env_file:
            - ../.env
        entrypoint: npm run dev
        ports:
            - 3000:3000
        volumes:
            - ../client:/app
        networks:
            - internal

networks:
    internal:
